### ISSUE TITLE
Toshiba API behaviour changed? Connection not working.

### ISSUE THREAD

**Issue by savimaki** [KaSroka/Toshiba-AC-control#48]
Copied from another issue (https://github.com/h4de5/home-assistant-toshiba_ac/issues/181), but it turns out the issue is with this repo:

I had the integration working but it suddenly went unavailable. My toshiba app still works. I tried reinstalling the integration but no dice. I only get "Unexpected error" when trying to download the integration and login with my credentials.
```Logger: custom_components.toshiba_ac.config_flow
Source: custom_components/toshiba_ac/config_flow.py:77
integration: Toshiba AC ([documentation](https://github.com/h4de5/home-assistant-toshiba_ac), [issues](https://github.com/h4de5/home-assistant-toshiba_ac/issues))
First occurred: 14:49:37 (1 occurrences)
Last logged: 14:49:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/toshiba_ac/config_flow.py", line 77, in async_step_user
    data = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toshiba_ac/config_flow.py", line 41, in validate_input
    sas_token = await device_manager.connect()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.local/lib/python3.12/site-packages/toshiba_ac/device_manager.py", line 58, in connect
    await self.http_api.connect()
  File "/config/.local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 116, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.local/lib/python3.12/site-packages/toshiba_ac/utils/http_api.py", line 98, in request_api
    json = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://mobileapi.toshibahomeaccontrols.com/api/Consumer/Login')

**Comment by felixmueller** [comment]
@savimaki, @KaSroka, @h4de5
I can confirm this issue in my setup.
It would be awesome if you could look into this @KaSroka as the cooling season ist just starting to begin ☀️❄️😬

**Comment by Lake292** [comment]
I can confirm as well, they probably made some change to the API. Will try to debug when I get a chance later today, to provide more details if I will find anything.

**Comment by felixmueller** [comment]
@savimaki @Lake292 I just tried to reload the HA integration and it started working again! Can you confirm?

**Comment by savimaki** [comment]
Confirmed working! Maybe an outage or someone was poking around in their production servers 🤣 Case closed!
